Traceback (most recent call last):
  File "/home/chris/Development/kirenz-mlops-semester/jupyter-book/venv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/chris/Development/kirenz-mlops-semester/jupyter-book/venv/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/chris/Development/kirenz-mlops-semester/jupyter-book/venv/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/chris/Development/kirenz-mlops-semester/jupyter-book/venv/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/chris/Development/kirenz-mlops-semester/jupyter-book/venv/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/chris/Development/kirenz-mlops-semester/jupyter-book/venv/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/chris/Development/kirenz-mlops-semester/jupyter-book/venv/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
jupyter-book build jupyter-book/
------------------

[0;36m  File [0;32m"/tmp/ipykernel_39052/3553495748.py"[0;36m, line [0;32m1[0m
[0;31m    jupyter-book build jupyter-book/[0m
[0m                 ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax

SyntaxError: invalid syntax (3553495748.py, line 1)

